### PR TITLE
Migrate CI/CD to Github actions, fix broken links examples

### PR DESCRIPTION
**Pull request by albincorreya**
This PR addresses mainly the changes related to the migration of CI/CD to GitHub actions and fix broken links in the example web demos.

- CI/CD migration #72 
- Fix broken links web examples #79 

Cheers to @jmarcosfer for the contributions :)

### CODE REVIEW

**Review by jmarcosfer — COMMENTED** [review]
Looks good, thanks @albincorreya! However, wait a bit please. I'll add a couple of things to `dev` so they can be merged on this same PR:
- We can add @ljoglar's audio problems detection demo, which is nearly integrated.
- I fixed a couple of small things on the new onsets demo.

**Comment by albincorreya** [comment]
@jmarcosfer Sure that is also fine.
We can also make a new PR for adding the new audio problem detection demo from @ljoglar :) Since this PR is mostly related to CI/CD migration and some other minor fixes to existing examples, I think it would be good to separate both additions in different PR.

**Comment by albincorreya** [comment]
@jmarcosfer  Sorry, just noticed that there are no pipelines running on any changes on the `dev` branch as I can see [here](https://github.com/MTG/essentia.js/actions).  According to your [setting](https://github.com/MTG/essentia.js/blob/dev/.github/workflows/integration.yml#L3), shouldn't it do that? Am I missing anything here?

**Comment by jmarcosfer** [comment]
@albincorreya Nope. Workflows only run on changes to source code or build config, and I don't think there have been any changes to `/src` or any of the main configuration files.

**Comment by albincorreya** [comment]
@jmarcosfer That make sense. Thanks for the clarification :)

**Review by jmarcosfer — APPROVED** [review]

**Pull request merged**
